// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvLpt7OsEarn7Eb-CaD4vHIPjMCXGkQWM',
    appId: '1:1047517326176:web:d38d601f9b691f496ecc05',
    messagingSenderId: '1047517326176',
    projectId: 'ast-blitz',
    authDomain: 'ast-blitz.firebaseapp.com',
    databaseURL: 'https://ast-blitz-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ast-blitz.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAuqP7Iq4SKNYxhENwy6TDSHjFyM9AFAk',
    appId: '1:1047517326176:android:99de76737357dfc86ecc05',
    messagingSenderId: '1047517326176',
    projectId: 'ast-blitz',
    databaseURL: 'https://ast-blitz-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ast-blitz.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYNcqivvKY0_8l42bLnGHdibw-itW6Ouo',
    appId: '1:1047517326176:ios:27e11bb2075c76406ecc05',
    messagingSenderId: '1047517326176',
    projectId: 'ast-blitz',
    databaseURL: 'https://ast-blitz-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ast-blitz.firebasestorage.app',
    iosClientId: '1047517326176-2de71lj1hpmvmcre6sbpobcj6uab6ht8.apps.googleusercontent.com',
    iosBundleId: 'com.astblitz.astBlitz',
  );

}